### ISSUE TITLE
打算开一个新分支用nodeJs重构整个项目

### ISSUE THREAD

**Issue by Ha2ryZhang** [Ha2ryZhang/alltv#6]

**Comment by SlotSun** [comment]
老哥我想问下怎么在服务器上搭建直播的api

**Comment by Ha2ryZhang** [comment]
> 老哥我想问下怎么在服务器上搭建直播的api

自己做直播吗

**Comment by SlotSun** [comment]
不是啊 ，就是学习怎么爬取那些直播房间的信息，想自己弄个聚合的加上电视台的直播源弄个聚合的自己看

**Comment by Ha2ryZhang** [comment]
> 不是啊 ，就是学习怎么爬取那些直播房间的信息，想自己弄个聚合的加上电视台的直播源弄个聚合的自己看

抓包分析慢慢来，,你可以看看这个[现成项目](https://github.com/wbt5/real-url) python写的，大部分都有了，自己搭个web服务就好

**Comment by SlotSun** [comment]
> > 不是啊 ，就是学习怎么爬取那些直播房间的信息，想自己弄个聚合的加上电视台的直播源弄个聚合的自己看
> 
> 抓包分析慢慢来，,你可以看看这个[现成项目](https://github.com/wbt5/real-url) python写的，大部分都有了，自己搭个web服务就好

我根据你的flutterapp做了一个搜索房间号简单获取直播源的然后播放的app有点简陋，想打磨一下弄上房间信息 ，搜到了[b站的api](https://github.com/SocialSisterYi/bilibili-API-collect)，但是斗鱼和虎牙的不知道怎么搞，所以很好奇怎么抓到的，是自己根据网页慢慢分析爬的吗？

**Comment by Ha2ryZhang** [comment]
> > > 不是啊 ，就是学习怎么爬取那些直播房间的信息，想自己弄个聚合的加上电视台的直播源弄个聚合的自己看
> > 
> > 
> > 抓包分析慢慢来，,你可以看看这个[现成项目](https://github.com/wbt5/real-url) python写的，大部分都有了，自己搭个web服务就好
> 
> 我根据你的flutterapp做了一个搜索房间号简单获取直播源的然后播放的app有点简陋，想打磨一下弄上房间信息 ，搜到了[b站的api](https://github.com/SocialSisterYi/bilibili-API-collect)，但是斗鱼和虎牙的不知道怎么搞，所以很好奇怎么抓到的，是自己根据网页慢慢分析爬的吗？

F12 慢慢分析 看network

**Comment by a1470852** [comment]
最新版下载链接多少啊

**Comment by Ha2ryZhang** [comment]
> 最新版下载链接多少啊
https://alltv.lanzoui.com/b01bexnha
